[package]
name = "netropy"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
bytes = "1.10"
tracing = "0.1"
tracing-subscriber = { version ="0.3" }
tokio = { version = "1.32", features = ["full"] }
rand = "0.9"
